
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tools
  labels:
    app: tools
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tools
  template:
    metadata:
      labels:
        app: tools
    spec:
      containers:
      - name: tools
        image: todddsm/alpine-tools:0.1
        imagePullPolicy: IfNotPresent
        # resources:
        #   requests:
        #     cpu: "100m"
        #     memory: "32M"
        #   limits:
        #     cpu: "200m"
        #     memory: "64M"
        ports:
        - containerPort: 22